// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;

public partial class AdminRelation
{
    [Key]
    public int Id { get; set; }

    public int User_Id { get; set; }

    public int Institution_Id { get; set; }

    [JsonIgnore]
    [ForeignKey("Institution_Id")]
    [InverseProperty("AdminRelations")]
    public virtual Institution Institution { get; set; }
    [JsonIgnore]
    [ForeignKey("User_Id")]
    [InverseProperty("AdminRelations")]
    public virtual User User { get; set; }
}