// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;

[Keyless]
[Table("AdminRelation")]
public partial class AdminRelation
{
    public int User_Id { get; set; }

    public int Institution_Id { get; set; }

    [ForeignKey("Institution_Id")]
    public virtual Instutution Institution { get; set; }

    [ForeignKey("User_Id")]
    public virtual User User { get; set; }
}