// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    public int Department_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int Institution_Id { get; set; }
    [JsonIgnore]
    [ForeignKey("Institution_Id")]
    [InverseProperty("Departments")]
    public virtual Instutution Institution { get; set; }
    [JsonIgnore]
    [InverseProperty("Department")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
    public void NameValidate()
    {
        if (Name == null)
        {
            throw new ArgumentNullException("Angiv venligst et navn");
        }
        if (Name.Length <= 5 || Name.Length >= 15)
        {
            throw new ArgumentOutOfRangeException("Navnet skal mindst være 2 tegn og maksimalt 15 tegn");
        }
    }

    public void DepartmentValidate()
    {
        NameValidate();
    }
}