// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Last_name { get; set; }

    public DateOnly? Birthday { get; set; }

    public int? Department_id { get; set; }

    [ForeignKey("Department_id")]
    [InverseProperty("Students")]
    public virtual Department Department { get; set; }
}