// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;
public enum Type_Log
{
    Arrived,
    Gone,
    Sick
}

[Keyless]
[Table("StudentLog")]
public partial class StudentLog
{
    public int Student_Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public Type_Log Type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [ForeignKey("Student_Id")]
    public virtual Student Student { get; set; }
}