// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;

[Keyless]
public partial class TeacherRelation
{
    public int User_id { get; set; }

    public int Department_id { get; set; }

    [ForeignKey("Department_id")]
    public virtual Department Department { get; set; }
}