// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;
public enum User_type
{
    Super_Admin,
    Admin,
    Padagogue,
    Parent
}
public partial class User
{
    [Key]
    public int User_Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string User_Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Last_name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    public int Zip_code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string E_mail { get; set; }

    public long Mobil_nr { get; set; }

    public User_type Usertype { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
    public void UsernameValidate()
    {
        if (User_Name == null)
        {
            throw new ArgumentNullException("Angiv venligst et navn");
        }
        if (User_Name.Length <= 5 || User_Name.Length >= 15)
        {
            throw new ArgumentOutOfRangeException("Brugernavnet skal mindst være 5 tegn og maksimalt 15 tegn");
        }
    }

    public void ZipCodeValidate()
    {
        if (Zip_code.ToString().Length == 4) // Zip Code konverteres til en streng med ToString()-metoden, og derefter kontrolleres længden af denne streng.
        {
            throw new ArgumentOutOfRangeException("Postnummeret skal være 4 tegn langt");
        }
    }

    public void PhoneNrValidate()
    {
        if (Mobil_nr <= 0)
        {
            throw new ArgumentOutOfRangeException("Mobilnummeret må ikke være nul eller negativt");
        }
        if (Mobil_nr < 10000000 || Mobil_nr > 999999999999)
        {
            throw new ArgumentOutOfRangeException("Mobilnummeret skal være mellem 8 og 12 cifre");
        }
    }
    public void UserValidate()
    {
        UsernameValidate();
        ZipCodeValidate();
        PhoneNrValidate();
    }
}


