// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyKidsReg.Models;
public enum User_type
{
    Super_Admin,
    Admin,
    Padagogue,
    Parent
}
public partial class User
{
    [Key]
    public int User_Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string User_Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Last_name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    public int Zip_code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string E_mail { get; set; }

    public long Mobil_nr { get; set; }

    public User_type Usertype { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}